### ISSUE TITLE
About the iam variables

### ISSUE THREAD

**Issue by danazkari** [KyMidd/Terraform_CI-CD_Bootstrap#1]
Hi there! I have a question regarding a few variables you have set but don't seem to use, are those going to be useful at some point or are they being used by some obscure feature that I haven't found yet?

```terraform
variable "iam_user_name" {}
variable "ado_iam_role_name" {}
variable "aws_iam_policy_permits_name" {}
variable "aws_iam_policy_assume_name" {}
```

**Comment by KyMidd** [comment]
Hey Daniel! Great point, these aren't used here. This is a version of this code: https://github.com/KyMidd/AzureDevOps_Terraform_AwsSeed/blob/master/modules/ado_seed/ado_seed_module.tf

In that one I build these resources, and also build an IAM role + policy with unrestricted access for terraform to assume. I

I'll remove these variables from here so they're less confusing. Thanks for the note!
